import { randomBytes } from "node:crypto";
import { isSecretLikeKey } from "../secretSafety";
import { normalizeRuntimeNodeId } from "./onlineRuntimeCoordinator";

interface PostgresQueryable {
  query(text: string, values?: unknown[]): Promise<{ rows: any[]; rowCount?: number }>;
}

export interface PostgresOnlineSpectatorPresenceStoreOptions {
  nodeId: string;
  queryable: PostgresQueryable;
  presenceTtlMs?: number;
  connectionIdFactory?: () => string;
}

export interface PostgresSpectatorPresenceRegistration {
  gameId: string;
  nodeId: string;
  connectionId: string;
  expiresAt: string;
}

const DEFAULT_SPECTATOR_PRESENCE_TTL_MS = 45_000;
const SPECTATOR_CONNECTION_ID_PATTERN = /^spectator_[A-Za-z0-9_-]{12,64}$/;

function normalizeSpectatorConnectionId(connectionId: string): string {
  const value = connectionId.trim();
  if (!SPECTATOR_CONNECTION_ID_PATTERN.test(value) || isSecretLikeKey(value)) {
    throw new Error(
      "PostgreSQL spectator connection id must be opaque, non-secret, and generated by the server."
    );
  }
  return value;
}

function rowToRegistration(row: any): PostgresSpectatorPresenceRegistration {
  if (
    typeof row?.game_id !== "string" ||
    typeof row.node_id !== "string" ||
    typeof row.connection_id !== "string"
  ) {
    throw new Error("Invalid PostgreSQL spectator presence row.");
  }
  const expiresAt =
    typeof row.expires_at === "string"
      ? new Date(row.expires_at)
      : row.expires_at instanceof Date
        ? row.expires_at
        : null;
  if (!expiresAt || Number.isNaN(expiresAt.getTime())) {
    throw new Error("Invalid PostgreSQL spectator presence expiry.");
  }
  return {
    gameId: row.game_id,
    nodeId: row.node_id,
    connectionId: normalizeSpectatorConnectionId(row.connection_id),
    expiresAt: expiresAt.toISOString(),
  };
}

export class PostgresOnlineSpectatorPresenceStore {
  private readonly nodeId: string;
  private readonly queryable: PostgresQueryable;
  private readonly presenceTtlMs: number;
  private readonly connectionIdFactory: () => string;
  private schemaReady?: Promise<void>;

  constructor(options: PostgresOnlineSpectatorPresenceStoreOptions) {
    this.nodeId = normalizeRuntimeNodeId(options.nodeId);
    this.queryable = options.queryable;
    this.presenceTtlMs = options.presenceTtlMs ?? DEFAULT_SPECTATOR_PRESENCE_TTL_MS;
    this.connectionIdFactory =
      options.connectionIdFactory ??
      (() => `spectator_${randomBytes(9).toString("base64url")}`);
    if (!Number.isSafeInteger(this.presenceTtlMs) || this.presenceTtlMs < 1) {
      throw new Error("PostgreSQL spectator presence TTL must be a positive integer.");
    }
  }

  async ensureSchema(): Promise<void> {
    this.schemaReady ??= this.createSchema().catch((error) => {
      this.schemaReady = undefined;
      throw error;
    });
    return this.schemaReady;
  }

  async registerSpectator(input: { gameId: string }): Promise<PostgresSpectatorPresenceRegistration> {
    await this.ensureSchema();
    const connectionId = normalizeSpectatorConnectionId(this.connectionIdFactory());
    const result = await this.queryable.query(
      `
        INSERT INTO online_spectator_presence (
          node_id,
          connection_id,
          game_id,
          expires_at,
          updated_at
        )
        VALUES ($1, $2, $3, now() + ($4::int * interval '1 millisecond'), now())
        ON CONFLICT (node_id, connection_id) DO UPDATE
        SET
          game_id = EXCLUDED.game_id,
          expires_at = EXCLUDED.expires_at,
          updated_at = now()
        RETURNING node_id, connection_id, game_id, expires_at
      `,
      [this.nodeId, connectionId, input.gameId, this.presenceTtlMs]
    );
    return rowToRegistration(result.rows[0]);
  }

  async refreshSpectator(input: {
    gameId: string;
    connectionId: string;
  }): Promise<PostgresSpectatorPresenceRegistration | null> {
    await this.ensureSchema();
    const connectionId = normalizeSpectatorConnectionId(input.connectionId);
    const result = await this.queryable.query(
      `
        UPDATE online_spectator_presence
        SET
          expires_at = now() + ($1::int * interval '1 millisecond'),
          updated_at = now()
        WHERE node_id = $2
          AND connection_id = $3
          AND game_id = $4
        RETURNING node_id, connection_id, game_id, expires_at
      `,
      [this.presenceTtlMs, this.nodeId, connectionId, input.gameId]
    );
    return result.rows[0] ? rowToRegistration(result.rows[0]) : null;
  }

  async removeSpectator(input: { gameId: string; connectionId: string }): Promise<void> {
    await this.ensureSchema();
    const connectionId = normalizeSpectatorConnectionId(input.connectionId);
    await this.queryable.query(
      `
        DELETE FROM online_spectator_presence
        WHERE node_id = $1
          AND connection_id = $2
          AND game_id = $3
      `,
      [this.nodeId, connectionId, input.gameId]
    );
  }

  async countSpectators(gameId: string): Promise<number> {
    await this.ensureSchema();
    const result = await this.queryable.query(
      `
        SELECT COUNT(*)::int AS count
        FROM online_spectator_presence
        WHERE game_id = $1
          AND expires_at > now()
      `,
      [gameId]
    );
    const count = result.rows[0]?.count;
    if (!Number.isSafeInteger(count) || count < 0) {
      throw new Error("Invalid PostgreSQL spectator count.");
    }
    return count;
  }

  async cleanupExpiredSpectators(): Promise<number> {
    await this.ensureSchema();
    const result = await this.queryable.query(
      `
        DELETE FROM online_spectator_presence
        WHERE expires_at <= now()
      `,
      []
    );
    return result.rowCount ?? 0;
  }

  private async createSchema(): Promise<void> {
    await this.queryable.query(`
      CREATE TABLE IF NOT EXISTS online_spectator_presence (
        node_id TEXT NOT NULL,
        connection_id TEXT NOT NULL,
        game_id TEXT NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (node_id, connection_id)
      )
    `);
    await this.queryable.query(`
      CREATE INDEX IF NOT EXISTS online_spectator_presence_game_expires_idx
        ON online_spectator_presence (game_id, expires_at)
    `);
    await this.queryable.query(`
      CREATE INDEX IF NOT EXISTS online_spectator_presence_expires_idx
        ON online_spectator_presence (expires_at)
    `);
  }
}
